#pragma once

struct ThreadData {
	ULONG ThreadID;
	int Priority;
};

#define PRIORITY_BOOSTER_DEVICE 0x8000
#define PRIORITY_BOOSTER_FUNCTION 0x800

#define IOCTL_PRIORITY_BOOSTER_SET_PRIORITY CTL_CODE(PRIORITY_BOOSTER_DEVICE, PRIORITY_BOOSTER_FUNCTION, METHOD_NEITHER, FILE_ANY_ACCESS)

